#!/bin/bash

. $(dirname $0)/functions.sh

#List of supported languages (used for profile)

LANGUAGES="ca-Catalan
cs-Czech
de-German
fr-French
el-Greek
en-English
es-Spanish
hi-Hindi
it-Italian
nl-Dutch
pl-Polish
pt-Portuguese
ru-Russian
sv-Swedish
vi-Vietnamese
zh-Chinese"

check_lang(){
	OK=""
	for LANGLINE in $LANGUAGES
	do
	  LANGCODE=$(echo $LANGLINE|sed 's/-.*//')
	  OK="$OK:$LANGCODE:"
	done
	echo $OK|grep -q $1
}

get_rhasspy_language(){
        DEFAULT=$1
        LANGUAGE=$DEFAULT
        confirm "Do you want to set the profile name to $LANGUAGE ? " ||
        while true
        do
		for LANG in $LANGUAGES
		do
			echo "	$LANG" |sed 's/-/ /' >>/dev/tty
		done
                echo -n "Enter language code: " >>/dev/tty
                read LANGUAGE
                [[ -z "$LANGUAGE" ]] && LANGUAGE=$DEFAULT
                check_lang $LANGUAGE || {
                        echo "Language $LANGUAGE not supported" >>/dev/tty
                        continue
                }
                confirm "Do you want to set the profile name to $LANGUAGE ? " && break
        done
        echo $LANGUAGE
}


#Defaults

RHASSPY=~/.config/rhasspy
RHASSPY_DATA="$RHASSPY/profiles"
CONTAINER_NAME=domoticz
ENVIRONMENT='-v "/etc/localtime:/etc/localtime:ro"'
PORTS="12101:12101"
REPOSITORY=rhasspy/rhasspy
RHASSPY_PROFILE=$(get_rhasspy_language en)
FIXED_ARG=""

# Check arguments
RESTART_ARG=$(get_restart)
DEVICES_ARG="--device /dev/snd:/dev/snd"
VOLUMES_ARG=$(get_volumes $RHASSPY_DATA:/profiles)
PORTMAP_ARG=$(get_ports "$PORTS")
CONTAINER_NAME_ARG=$(get_containername rhasspy_$RHASSPY_PROFILE)
CONTAINER_ARGS="--user-profiles /profiles --profile $RHASSPY_PROFILE"

# Run docker
ALL_ARGS="$RESTART_ARG $PORTMAP_ARG $VOLUMES_ARG $DEVICES_ARG"
ALL_ARGS="$ALL_ARGS $CONTAINER_NAME_ARG $ENVIRONMENT"
ALL_ARGS="$ALL_ARGS $REPOSITORY $CONTAINER_ARGS"
confirm "Do you want to start Rhasspy with arguments '$ALL_ARGS' ? " &&
docker run -d $ALL_ARGS

exit 0

