#!/bin/bash

. $(dirname $0)/functions.sh

#Defaults

DOMOTICZ_DATA=~/domoticz
CONTAINER_NAME=domoticz
ENVIRONMENT="-e TZ=$(cat /etc/timezone)"
PORTS="8080:8080 8443:443"
REPOSITORY=domoticz/domoticz

# Check arguments
RESTART_ARG=$(get_restart)
DEVICES_ARG=$(get_devices)
VOLUMES_ARG=$(get_volumes $DOMOTICZ_DATA:/opt/domoticz/userdata)
PORTMAP_ARG=$(get_ports "$PORTS")
CONTAINER_NAME_ARG=$(get_containername domoticz)
CONTAINER_ARGS=""

# Run docker
ALL_ARGS="$RESTART_ARG $PORTMAP_ARG $VOLUMES_ARG $DEVICES_ARG $CONTAINER_NAME_ARG $ENVIRONMENT $REPOSITORY $CONTAINER_ARGS"
confirm "Do you want to start Domoticz with arguments '$ALL_ARGS' ? " &&
docker run -d $ALL_ARGS

exit 0

