#!/bin/bash

. $(dirname $0)/functions.sh

DEVICES=$(get_devices)

DOMOTICZ=~/domoticz
[[ -d $DOMOTICZ ]] || { confirm "Do you want me to create directory '$DOMOTICZ' ?" && mkdir $DOMOTICZ || exit 1 ; }

TZ=$(cat /etc/timezone)

CONTAINER_NAME=$(get_containername domoticz)

confirm "Do you want to start Domoticz with devices '$DEVICES' and containername '$CONTAINER_NAME' ? " &&
docker run -d \
    --restart unless-stopped \
    -p 8080:8080 \
    -p 8443:443 \
    -v $DOMOTICZ:/opt/domoticz/userdata \
    -e TZ=$TZ \
    $DEVICES \
    --name=$CONTAINER_NAME \
    domoticz/domoticz

exit 0

