#!/bin/bash
#Copyright 2021 - Albert Montijn (montijnalbert@gmail.com)
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   ---------------------------------------------------------------------------
#   Programming is the result of learning from others and making errors.
#   A good programmer often follows the tips and tricks of better programmers.
#   The solution of a problem seldom leads to new or original code.
#   So any resemblance to already existing code is purely coincidental
#

# Check the system for installation of docker, docker-compose and pip3
# If the package does not exist, install it
# The installation must be done as root. Therefore the script calls itself running sudo
# This will only succeed when the calling user is on the sudoers list

do_execute() {
	echo "======= executing ======" "$@" "========================="
	"$@"
	echo "======= executing ======" "$@" "========= done =========="
}

exec_exists() {
	echo -n "Check if $1 exists"
	if $1 --version >/dev/null 2>&1
	then 
		echo ". OK"
	else
		echo ". Missing"
		false
	fi
}

main (){
	echo "Running system-check"
	do_execute apt-get update
	do_execute apt full-upgrade

	# Install docker-compose  
	# The simplest way to install docker-compose (after installing docker) is by using pip (package installer for Python).  
	# Make sure you have pip3 installed
	exec_exists docker || do_execute apt install docker 
	exec_exists pip3 || do_execute apt install python3-pip
	exec_exists docker-compose || do_execute pip3 install docker-compose  
}

if [ $(whoami) == root ]
then
        main
else
        echo "This script needs root privileges, Switching to root..."
        sudo --preserve-env=HOME $0
fi


